# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Slider'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name_plural': 'Training'},
        ),
    ]
