# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-06 10:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default=1, null=True, upload_to='collage')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slider', models.ImageField(blank=True, default=1, null=True, upload_to='we-offer')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('ticker', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='We_offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('training_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('weoffer_image', models.ImageField(blank=True, default=1, null=True, upload_to='we-offer')),
            ],
        ),
    ]
