# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-06 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collage',
            options={'verbose_name_plural': 'Collage'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Slider'},
        ),
        migrations.AlterModelOptions(
            name='ticker',
            options={'verbose_name_plural': 'Ticker'},
        ),
        migrations.AlterModelOptions(
            name='we_offer',
            options={'verbose_name': 'We offer', 'verbose_name_plural': 'We offer'},
        ),
    ]
