# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180106_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider',
            field=models.ImageField(blank=True, default=1, null=True, upload_to='home'),
        ),
    ]
