# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-06 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name_plural': 'Servicetype maintitle'},
        ),
        migrations.AlterModelOptions(
            name='subtitle',
            options={'verbose_name_plural': 'Subtitle'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name_plural': 'Tool'},
        ),
    ]
