# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-06 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20180106_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human_resource',
            options={'verbose_name': 'Human resource', 'verbose_name_plural': 'Human resource'},
        ),
    ]
