# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 06:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(blank=True, default=1, null=True, upload_to='survey-detail')),
                ('location', models.ImageField(blank=True, default=1, null=True, upload_to='survey-detail')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Publication_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_link', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Publication link',
                'verbose_name_plural': 'Publication link',
            },
        ),
        migrations.CreateModel(
            name='Survey_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('survey_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update', models.DateField()),
                ('project_description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Survey detail',
                'verbose_name_plural': 'Survey detail',
            },
        ),
    ]
