# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-06 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, null=True, unique=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('time_period', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, null=True, verbose_name='year')),
                ('funding_agency', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Major work',
                'verbose_name': 'Major work',
            },
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('time_period', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, null=True, verbose_name='year')),
                ('funding_agency', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Upcoming',
            },
        ),
        migrations.CreateModel(
            name='Work_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, max_length=100, null=True)),
                ('time_period', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, null=True, verbose_name='year')),
                ('funding_agency', models.CharField(blank=True, max_length=100, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Work progress',
                'verbose_name': 'Work progress',
            },
        ),
    ]
