# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-06 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcoming',
            options={'verbose_name_plural': 'Upcoming work'},
        ),
        migrations.AlterModelOptions(
            name='work_progress',
            options={'verbose_name': 'Work progress', 'verbose_name_plural': 'Work in progress'},
        ),
    ]
